[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_ENV = "production"
  NETLIFY_ENV = "production"
  DATABASE_URL = "$DATABASE_URL"

[context.production.environment]
  NODE_ENV = "production"
  NETLIFY_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NETLIFY_ENV = "deploy-preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NETLIFY_ENV = "branch-deploy"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"